name: CI workflow for both todo and auth API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 9.x, 10.x, 12.x]


    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - name: Set Node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # Jobs for todo-api
      - name: check that every files were checked out
        working-directory: ${{ github.workspace }}/todo-api
        run: ls -la

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          npm install

      - name: Build source with babel support
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          npm install --only=dev
          npm run dist

      - name: perform API sanity check
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          cd lib && ls -la
          npm run check

      - name: unit tests
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          uptime


      #Jobs for auth-api
      - name: check that every files were checked out
        working-directory: ${{ github.workspace }}/auth-api
        run: ls -la

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/auth-api
        run: |
          npm install

      - name: Build source with babel support
        working-directory: ${{ github.workspace }}/auth-api
        run: |
          npm run dist

      - name: perform API sanity check
        working-directory: ${{ github.workspace }}/auth-api
        run: |
          cd lib && ls -la
          npm run check

      - name: unit tests
        working-directory: ${{ github.workspace }}/auth-api
        run: |
          uptime

#source: https://github.community/t5/GitHub-Actions/Github-actions-working-directory-incorrectly-documented/td-p/29201
