name: Deploy Gatsby Website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Build site assets
        working-directory: ${{ github.workspace }}
        run: ls -la

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          npm ci

      - name: Build
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          npm run build

      - name: Deploy
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          cd lib && ls -la
#source: https://github.community/t5/GitHub-Actions/Github-actions-working-directory-incorrectly-documented/td-p/29201