#---
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "Set Node ${{ matrix.node-version }}"
        uses: actions/setup-node@master
        with:
          node-version: "${{ matrix.node-version }}"
      -
        name: "Prepare environnement by install babel before building"
        run: "npm install babel-cli -g"
        working-directory: "${{ github.workspace }}/todo-api"
      -
        name: "check that every files were checked out"
        run: |
          cd todo-api
          ls -la
          cd ..
          cd auth-api
          ls -la
        working-directory: "${{ github.workspace }}"
      -
        name: "Install dependencies"
        run: |
          cd todo-api
          npm install
          cd ..
          cd auth-api
          npm install
        working-directory: "${{ github.workspace }}"
      -
        env:
          DB: "mongodb://localhost/user-DB"
          NODE_ENV: Test
          port: 4268
        name: "Build auth-api with babel support"
        run: "npm run dist"
        working_directory: "${{ github.workspace }}/auth-api"
      -
        env:
          DB: "mongodb://localhost/todo-DB"
          NODE_ENV: Test
          port: 4267
        name: "Build todo-api with babel support"
        run: "npm run dist"
        working_directory: "${{ github.workspace }}/todo-api"
    strategy:
      matrix:
        node-version:
          - 8.x
          - 9.x
          - 10.x
          - 12.x
name: "CI workflow for both todo and auth API"
true:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
