name: Deploy Gatsby Website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      # Jobs for todo-api
      - name: check that every files were checked out
        working-directory: ${{ github.workspace }}/todo-api
        run: ls -la

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          npm ci

      - name: Build source with babel support
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          npm run build

      - name: perform API sanity check
        working-directory: ${{ github.workspace }}/todo-api
        run: |
          cd lib && ls -la
          npm run check

        #Jobs for auth-api
        - name: check that every files were checked out
          working-directory: ${{ github.workspace }}/auth-api
          run: ls -la

        - name: Install dependencies
          working-directory: ${{ github.workspace }}/auth-api
          run: |
            npm ci

        - name: Build source with babel support
          working-directory: ${{ github.workspace }}/auth-api
          run: |
            npm run build

        - name: perform API sanity check
          working-directory: ${{ github.workspace }}/auth-api
          run: |
            cd lib && ls -la
            npm run check
#source: https://github.community/t5/GitHub-Actions/Github-actions-working-directory-incorrectly-documented/td-p/29201